# Generated by Django 3.2.9 on 2021-11-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('MERGED', 'Merged')], default='OPEN', max_length=15)),
                ('author', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('MERGED', 'Merged')], default='OPEN', max_length=255)),
                ('title', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('MERGED', 'Merged')], default='OPEN', max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
