# Generated by Django 3.2.9 on 2021-11-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_api', '0003_auto_20211123_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequest',
            name='base_branch',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='pullrequest',
            name='rebase_branch',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
