name: Deploy Master
on:
  push:
    branches:
      - master

jobs:

  release:
    runs-on: ubuntu-latest
    concurrency: release
    outputs:
      tag: ${{ steps.release.outputs.tag }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Python Semantic Release
      uses: relekang/python-semantic-release@v7.19.2
      with:
        github_token: ${{ secrets.GH_TOKEN }}

    - name: Expose Release
      id: expose-release
      run: echo "::set-output name=tag::$RELEASE_VERSION"
